configuration: Release
image: Visual Studio 2017
  
version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
  - gh-pages
  - 2.x

services:
- mssql2016
- mysql
- postgresql

nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
- cmd: build.cmd Pack

test: off

artifacts:
- path: artifacts/*.nupkg
  name: NuGet
- path: artifacts/*.zip
  name: Zip

deploy:
- provider: NuGet
  server: https://www.myget.org/F/quartznet/api/v2/package
  api_key:
    secure: vXa9bqFD68eDW9epKh/lUK/h1OdIL92RiKAbc+JfVarllY962DWqMNSKOdvCopy/
  skip_symbols: true
  on:
    branch: master
